yatta!
IS213-G9-tokyobanana/carbon-marketplace-backend pull request #1
Opened 2023-03-02 17:03 UTC by nicamanas

basic express app ready
postgresql database container created too

basic get route + manual code to add data in singular fashion

2023-03-03 03:18 UTC, DavidLHW requested changes
thanks for the pr! overall looks great and this should be enough for our use case (acting as a template to be used for other microservices)


- [ ] the express project files (package.json, package-lock, tsconfig etc) should reside inside the `./templates/express` directory instead of at the repo root
- [ ] compiled js files should not be pushed to repo (compile to `./express/dist/` and gitignored.) refer to [node-express-prisma boilerplate project](https://github.com/mcnaveen/Node-Express-Prisma-Boilerplate)

other than the above, the rest lgtm!

2023-03-04 07:37 UTC, nicamanas commented on package.json
> +}
have shifted course files into templates/express, testing with the docker compose up postgres database, data is persisted

![image](https://user-images.githubusercontent.com/16086138/222882724-1ce55792-8c24-44e9-8495-f2b744c6dadf.png)

![image](https://user-images.githubusercontent.com/16086138/222882737-c43a85cc-c7ad-4508-9342-be9a0e9c4dd6.png)

2023-03-04 07:40 UTC, nicamanas commented on templates/express/index.js
> +});
removed the js file, updated dependencies.

2023-03-04 15:35 UTC, DavidLHW reviewed
thanks for the changes! can i trouble you to add a readme on how to get started with this template project?

(we will use this template for all the microservices with express/typescript)

2023-03-04 15:35 UTC, DavidLHW commented on templates/express/package.json
> +{
should include the following in the `package.json`:

```json
{
  "name": "carbon-marketplace-express-microservice",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "npm run build && node ./dist/index.js",
    "dev": "nodemon ./src/index.ts",
    "build": "tsc -p ."
  }
}
```

2023-03-06 11:26 UTC, DavidLHW approved these changes
CLGTM @ be86f518c4178cc29c14f70e1b9beff12b9f312c

2023-03-06 11:27 UTC, merged